spring:
  thymeleaf:
    cache: false
  data:
    #mongodb:
      #uri: mongodb://sa:P%40ssword1@localhost:27017/tacoclouddb
    #cassandra:
      #keyspace-name: tacocloud
      #schema-action: create_if_not_exists
      #local-datacenter: Mars  # run cqlsh on your Cassandra, to get data center name
      #contact-points: # a contact point is the host where Cassandra node is running
      #- {your host}
      #port: 9042
      #username: cassandra
      #password: cassandra
      #connection:
        #init-query-timeout: 30s
        #connection-timeout: 5s
        #connect-timeout: 5s
  datasource:
    generate-unique-name: false
    name: tacocloud
    #url: jdbc:mysql://localhost:3306/TACODB?useSSL=true
    #username: root
    #password: P@ssoword1
    #driver-class-name: com.mysql.jdbc.Driver
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
